server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jchyng/MSA-Study
#private일 경우
# username:
# password: