#실행 포트 지정
server:
  port: 8761

#micro service의 id를 discovery-server로 지정
spring:
  application:
    name: discovery-Server

#Eureka Server인데 Client 설정을 하는 이유:
#유레카 라이브러리가 포함돼있으면 스프링 실행 시 유레카 클라이언트로 등록되기 때문에
eureka:
  client:
    register-with-eureka: false   #유레카 레지스트리에 자기 자신을 등록하지 않겠다.
    fetch-registry: false         #레지스트리의 정보를 가저오지 않겠다.
